type: bitsandbytes.optim.AdamW8bit
param_groups:
  backbone:
    lr: ${optimizer.param_groups.default.lr}
    weight_decay: 0.0
    weight_decay_bias: 0.0
    betas: [0.9, 0.95]
    eps: 1.0e-8
    # scheduler
    start_lr: 0
    end_lr: 0
  cross:
    lr: ${eval:'${optimizer.param_groups.default.lr} * 5'}
    weight_decay: 0.2
    weight_decay_bias: 0.0
    betas: [0.9, 0.98]
    eps: 1.0e-8
    # scheduler
    start_lr: 0
    end_lr: 0
  classifier:
    lr: ${eval:'${optimizer.param_groups.default.lr} * 5'}
    weight_decay: 0.2
    weight_decay_bias: 0.0
    betas: [0.9, 0.98]
    eps: 1.0e-8
    # scheduler
    start_lr: 0
    end_lr: 0
  simclr:
    lr: ${eval:'${optimizer.param_groups.default.lr} * 5'}
    weight_decay: 0.2
    weight_decay_bias: 0.0
    betas: [0.9, 0.98]
    eps: 1.0e-8
    # scheduler
    start_lr: 0
    end_lr: 0
  default:
    lr: 1e-4
    weight_decay: 0.0
    weight_decay_bias: 0.0
    betas: [0.9, 0.95]
    eps: 1.0e-8
    # scheduler
    start_lr: 0
    end_lr: 0
