type: torch.optim.AdamW
param_groups:
  default:
    lr: 1e−5
    weight_decay: 0.02
    weight_decay_bias: 0.0
    betas: [0.9, 0.98]
    eps: 1.0e-8
    # scheduler
    start_lr: 1.0e-6
    end_lr: 5.0e-6
