# Model Settings
backbone_path: siglip_checkpoints
training: true
val_dataset: false
temperature: 0.02
img_aug: true
cmt_depth: 4
lr_factor: 5.0
MLM: true
loss_names:
  - sdm
  - id
  - mlm
  # - itc
  # - cmpm
mlm_loss_weight: 1.0
id_loss_weight: 1.0
img_size:
  - 384
  - 128
interpolate_pos_encoding: true
stride_size: 16

text_length: 64
vocab_size: 250001

optimizer: AdamW8bit
lr: 1e-6
bias_lr_factor: 2.
momentum: 0.9
weight_decay: 4e-5
weight_decay_bias: 0.
alpha: 0.9
beta: 0.999

num_epochs: 120
milestones: [20, 50]
gamma: 0.1
warmup_factor: 0.1
warmup_epochs: 5
warmup_method: linear
lrscheduler: cosine
target_lr: 0
power: 0.9

dataset_name: VN3K
sampler: random
num_intance: 4
root_dir: .
batch_size: 1
test_batch_size: 64
num_workers: 4
# accumulate_grad_batches: 2
accelerator: gpu
