# ckpt_path:
default_root_dir: ./logs
max_epochs: 5
precision: bf16-mixed
accumulate_grad_batches: 1
accelerator: gpu
gradient_clip_val: 1.0
gradient_clip_algorithm: value
log_every_n_steps: 1
detect_anomaly: false
enable_progress_bar: true
enable_model_summary: true
enable_checkpointing: true
# fast_dev_run: 16
num_sanity_val_steps: 0
# check_val_every_n_epoch: 1
# overfit_batches: 10
