# config/config.yaml
defaults:
  - _self_
  - dataset: cuhk_pedes_10_percent
  - loss: best_msiglip
  - aug: siglip
  - trainer: best_msiglip
  - optimizer: tbps_clip_no_decay
  - scheduler: tbps_clip
  - tokenizer: m_siglip
  - backbone: m_siglip
  - logger: default

training: true
dataset_root_dir: .
distributed: false
img_size_st: "(256, 256)"
img_size: ${eval:${img_size_st}}
seed: 2307
