# config/config.yaml
defaults:
  - _self_
  - dataset: siglip_vn3k_vi
  - loss: siglip
  - aug: tbps_clip
  - trainer: siglip
  - optimizer: siglip
  - scheduler: siglip
  - tokenizer: siglip
  - backbone: siglip
  - logger: default

training: true
dataset_root_dir: .
distributed: false
img_size: ${tuple:384, 128}
seed: 2307
