# config/logger/default.yaml
checkpoint_log_dir: "logs/"
experiment_name: null # Will be dynamically set in the Python script

# Checkpoint settings
checkpoint:
  monitor: "eval_score"
  mode: "max"
  save_top_k: 3
  save_last: true
  filename: "{epoch}-{eval_score:.2f}"

# # TensorBoard specific settings
# tensorboard: {}
  # flush_secs: 120
  # max_queue: 10
logger_type: "wandb"

# Logging settings
console:
  level: "INFO"
file:
  level: "DEBUG"
  filename: "train.log"
